# Generated by Django 6.0.2 on 2026-02-20 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_alter_manufacturer_name_alter_medicine_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labreport',
            old_name='file',
            new_name='report_file',
        ),
        migrations.AlterField(
            model_name='labreport',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='medicines.medicine'),
        ),
    ]
