# Generated by Django 6.0.2 on 2026-03-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_alter_manufacturer_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
