# Generated by Django 6.0.2 on 2026-03-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_medicine_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='formula',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
