# Generated by Django 6.0.2 on 2026-03-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_medicine_formula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='description',
            new_name='address',
        ),
    ]
