# Generated by Django 6.0.2 on 2026-03-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0006_rename_description_manufacturer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
