# Generated by Django 6.0.2 on 2026-03-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0009_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=100, null=True),
        ),
    ]
