# Generated by Django 6.0.2 on 2026-03-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0010_medicine_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
